### ISSUE TITLE
Cross language display in entry lists

### ISSUE THREAD

**Issue by aVandalInShorts** [DeuxHuitHuit/multilingual_field#62]
I'm working on a project with the multilingual field and I've set the required languages to the main language. In the current situation, the main language is french and my Symphony is set to English. Therefore, I can only see "None" in the entry list for the field because it cannot detect the current language.

So I thought it would be cool if it could display the value of the other language if no value in the current language is detected. It could be shown as "Foo Bar (Fr)".

Cheers!

**Comment by nitriques** [comment]
I think it should still respect the "Use value from main language if selected language has empty value" option.

**Comment by nitriques** [comment]
It was already using the option.

BUT: In the case where the main language is empty (and not required), we will try the first required language we can find.
