### ISSUE TITLE
Optionnal message when the there is only one required language

### ISSUE THREAD

**Issue by aVandalInShorts** [DeuxHuitHuit/multilingual_field#64]
In the section builder page, when you select only one language in the required language field,  the message displayed in the entry builder page is "Optionnal" but it ain't.

It would be nice if it was written "Required in French" or "Required in Main Language [French]" or "Optionnal, exept for French"

:+1: :hash: :frog:

**Comment by nitriques** [comment]
I went with "LANG is optional" or even "LANG1, LANG2 are optional"
