### ISSUE TITLE
Can't see the check "Display in entries table"

### ISSUE THREAD

**Issue by DaveRev** [DeuxHuitHuit/multilingual_field#65]
Hi there, I'm using symphony 2.5.2 with frontend localisation 2.6.0 and multilingual text box 3.4.0, and when I edit or create a multilingual text box field, I can't see the checkbox "Display in entries table".
So these fields aren't displayed on entries table.
Do you have this issue?

**Comment by jonmifsud** [comment]
Yes I can replicate will try to send a PR for this issue today.

**Comment by nitriques** [comment]
Fixed in dev! Will release 3.4.1 today.
