### ISSUE TITLE
XML Importer Fails

### ISSUE THREAD

**Issue by peterfleck** [DeuxHuitHuit/multilingual_field#73]
I tried using XML Importer into this, it failed at line 527. I don't know if it is feasible to use XML Importer with the Multilingual fields? Thanks. 

522                 if (!isset($data[$lc]) && $entry_id) {
523                     continue;
524                 }
525
526                 // if one language fails, all fail
**527                 if (self::__OK__ != parent::checkPostFieldData($data[$lc], $file_message, $entry_id)) {**
528
529                     $local_msg = "<br />[$lc] {$all_langs[$lc]}: {$file_message}";
530
531                     if ($lc === $main_lang) {

**Comment by nitriques** [comment]
>  I don't know if it is feasible to use XML Importer with the Multilingual fields

I do not know either, that's the sad part. Maybe @jonmifsud knows ?

What XML are you feeding it ?

**Comment by peterfleck** [comment]
Thanks,

I need to follow the ONIX XML standard and have just started building.
I have a Country section that has a unique field for identification and then the Country name is a multilingual field.
I was importing the English from this file http://www.editeur.org/files/ONIX%20for%20books%20-%20code%20lists/ONIX_BookProduct_Codelists_Issue_34.xml matching on //CodeList[CodeListNumber="91"].
For Spanish I was importing from https://dilve.es/dilve/getArchivoDocumentacion.do?iddocumento=2123

I need to use a number of the Lists from these files and don't want to have to entry them manually. The XML Importer seemed a great solution.

Thanks for your help

**Comment by wdebusschere** [comment]
Peter, we do multi language with the XML importer by adding a function in the class.xmlimporterhelpers.php.
We use it for example to update the Translations (section) for all our clients CMS, we update the CMS code and do an XML import so all CMS translations are everywhere the same..

We are not PHP programmers, but it works:

static function makeMultilanguage($string)
{	
	$xml = @simplexml_load_string($string);
	$xml = simplexml_load_string('<root>'.$string.'</root>');
	$result = $xml->xpath('//item');
	$output = array();
	$output['nl'] = $result[0];
	$output['en'] = $result[1];
	$output['fr'] = $result[2];		
	$output['pt'] = $result[3];
	return $output;
}

XML:
<translation>
<keyword handle="location">location</keyword>
<type>
<item handle="cms">cms</item>
</type>
<title mode="all-languages: unformatted">
<item lang="nl" handle="ligging" word-count="1" xml:lang="nl">Ligging</item>
<item lang="en" handle="location" word-count="1" xml:lang="en">Location</item>
<item lang="fr" handle="localisation" word-count="1" xml:lang="fr">Localisation</item>
<item lang="pt" handle="localizacao" word-count="1" xml:lang="pt">Localização</item>
</title>
</translation>

If you have a unique number per item, you can import your file per language and update..

**Comment by nitriques** [comment]
> I need to follow the ONIX XML

Been there, done that. What an awefull experience. But yeah, the solution is like @wdebusschere said. You need to have all the data in the same file.
