### ISSUE TITLE
Preferences not saved

### ISSUE THREAD

**Issue by jurajkapsz** [DeuxHuitHuit/multilingual_field#76]
Extension option `Consolidate entry data` in Symphony's Preferences has no effect - preference can't be changed nor when changed manually in `config.php`, it does not reflect the config's value (if `no` means `false`).

		###### MULTILINGUAL_FIELD ######
		'multilingual_field' => array(
			'consolidate' => 'no',
		),
		########

**Comment by nitriques** [comment]
Thanks for reporting. Will try to fix ASAP

**Comment by jurajkapsz** [comment]
This is the same also for the Multilingual Checkbox Field, as they I think share the same parts of code. Should I report it there too?

**Comment by jurajkapsz** [comment]
Thanks.

**Comment by nitriques** [comment]
> Should I report it there too?

No I'll check on that field and port the fix ;) Thanks !

**Comment by nitriques** [comment]
@jurajkapsz I did not wrote that part of the code, and the only thing I can say is that is not saving the value "by design". The default option (which is to consolidate) should always be on, since it may delete old language data. It would be dangerous to handle it.

I'll commit a patch for prevent it from being ever saved in the config.php file. Thanks.

**Comment by jurajkapsz** [comment]
> The default option (which is to consolidate) should always be on

Aha, I see, so its an one time action (of cleanup old language data) rather then a preference. Ok.

**Comment by nitriques** [comment]
Exactly. Fixed and released in `3.5.11` !

**Comment by jurajkapsz** [comment]
Great, thanks!

**Comment by nitriques** [comment]
(BTW, you need to manually delete the data in the config file, or they will keep popping up. But if you remove them, they will never come back (nor should they ever be there on new installs)

**Comment by jurajkapsz** [comment]
Thanks for the info!

**Comment by nitriques** [comment]
No problem!
