### ISSUE TITLE
Handles are unique even if not opted

### ISSUE THREAD

**Issue by jurajkapsz** [DeuxHuitHuit/multilingual_field#77]
**Issue:**

Unlike [Text Box](https://github.com/symphonists/textboxfield), handles are returned always unique, whether the `Handles are unique` option is selected or not.

![image](https://user-images.githubusercontent.com/2209893/28766881-d10e8dda-75d1-11e7-965a-ff68bd427461.png)

**Expected:**

Handles should be able to not to be unique.

(Edited) **Use case:**

I get unwanted suffixes into page `URL`s which are build from ML TB handles.

**Comment by nitriques** [comment]
Thanks for reporting! I never had ported it ! Fixed and released in 3.5.12

**Comment by jurajkapsz** [comment]
Thanks @nitriques , works great!
